name: whatsapp_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/images/appicon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf
